export const APP_GENERATE_TOKEN_REQUEST = "APP_GENERATE_TOKEN_REQUEST";
export const APP_GENERATE_TOKEN_SUCCESS = "APP_GENERATE_TOKEN_SUCCESS";
export const APP_GENERATE_TOKEN_FAILURE = "APP_GENERATE_TOKEN_FAILURE";

export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAILURE = "REGISTER_USER_FAILURE";

export const REGISTER_USER_CONFIRM_REQUEST = "REGISTER_USER_CONFIRM_REQUEST";
export const REGISTER_USER_CONFIRM_SUCCESS = "REGISTER_USER_CONFIRM_SUCCESS";
export const REGISTER_USER_CONFIRM_FAILURE = "REGISTER_USER_CONFIRM_FAILURE";

export const REGISTER_USER_CONFIRM_PIN_REQUEST =
  "REGISTER_USER_CONFIRM_PIN_REQUEST";
export const REGISTER_USER_CONFIRM_PIN_SUCCESS =
  "REGISTER_USER_CONFIRM_PIN_SUCCESS";
export const REGISTER_USER_CONFIRM_PIN_FAILURE =
  "REGISTER_USER_CONFIRM_PIN_FAILURE";

export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE";

export const LOGIN_USER_CONFIRM_PIN_REQUEST = "LOGIN_USER_CONFIRM_PIN_REQUEST";
export const LOGIN_USER_CONFIRM_PIN_SUCCESS = "LOGIN_USER_CONFIRM_PIN_SUCCESS";
export const LOGIN_USER_CONFIRM_PIN_FAILURE = "LOGIN_USER_CONFIRM_PIN_FAILURE";

export const LOGOUT = "LOGOUT";

export const FORGOT_USER_MPIN_REQUEST = "FORGOT_USER_MPIN_REQUEST";
export const FORGOT_USER_MPIN_SUCCESS = "FORGOT_USER_MPIN_SUCCESS";
export const FORGOT_USER_MPIN_FAILURE = "FORGOT_USER_MPIN_FAILURE";

export const RESET_USER_MPIN_REQUEST = "RESET_USER_MPIN_REQUEST";
export const RESET_USER_MPIN_SUCCESS = "RESET_USER_MPIN_SUCCESS";
export const RESET_USER_MPIN_FAILURE = "RESET_USER_MPIN_FAILURE";

export const EDIT_PROFILE_USER_REQUEST = "EDIT_PROFILE_USER_REQUEST";
export const EDIT_PROFILE_USER_SUCCESS = "EDIT_PROFILE_USER_SUCCESS";
export const EDIT_PROFILE_USER_FAILURE = "EDIT_PROFILE_USER_FAILURE";

export const UPDATE_PROFILE_USER_REQUEST = "UPDATE_PROFILE_USER_REQUEST";
export const UPDATE_PROFILE_USER_SUCCESS = "UPDATE_PROFILE_USER_SUCCESS";
export const UPDATE_PROFILE_USER_FAILURE = "UPDATE_PROFILE_USER_FAILURE";

export const SEARCH_USER_REQUEST = "SEARCH_USER_REQUEST";
export const SEARCH_USER_SUCCESS = "SEARCH_USER_SUCCESS";
export const SEARCH_USER_FAILURE = "SEARCH_USER_FAILURE";

export const LIST_CONVERSATION_REQUEST = "LIST_CONVERSATION_REQUEST";
export const LIST_CONVERSATION_SUCCESS = "LIST_CONVERSATION_SUCCESS";
export const LIST_CONVERSATION_FAILURE = "LIST_CONVERSATION_FAILURE";

export const LIST_MESSAGES_REQUEST = "LIST_MESSAGES_REQUEST";
export const LIST_MESSAGES_SUCCESS = "LIST_MESSAGES_SUCCESS";
export const LIST_MESSAGES_FAILURE = "LIST_MESSAGES_FAILURE";

export const SEND_MESSAGE_REQUEST = "SEND_MESSAGE_REQUEST";
export const SEND_MESSAGE_SUCCESS = "SEND_MESSAGE_SUCCESS";
export const SEND_MESSAGE_FAILURE = "SEND_MESSAGE_FAILURE";

export const CREATE_CONVERSATION_REQUEST = "CREATE_CONVERSATION_REQUEST";
export const CREATE_CONVERSATION_SUCCESS = "CREATE_CONVERSATION_SUCCESS";
export const CREATE_CONVERSATION_FAILURE = "CREATE_CONVERSATION_FAILURE";

export const CHECK_FLAMES_REQUEST = "CHECK_FLAMES_REQUEST";
export const CHECK_FLAMES_SUCCESS = "CHECK_FLAMES_SUCCESS";
export const CHECK_FLAMES_FAILURE = "CHECK_FLAMES_FAILURE";

export const CREATE_COMMUNITY_REQUEST = "CREATE_COMMUNITY_REQUEST";
export const CREATE_COMMUNITY_SUCCESS = "CREATE_COMMUNITY_SUCCESS";
export const CREATE_COMMUNITY_FAILURE = "CREATE_COMMUNITY_FAILURE";

export const ADD_GROUP_COMMUNITY_REQUEST = "ADD_GROUP_COMMUNITY_REQUEST";
export const ADD_GROUP_COMMUNITY_SUCCESS = "ADD_GROUP_COMMUNITY_SUCCESS";
export const ADD_GROUP_COMMUNITY_FAILURE = "ADD_GROUP_COMMUNITY_FAILURE";

export const UPDATE_PROFILE_USER_NEW_PHONE_REQUEST =
  "UPDATE_PROFILE_USER_NEW_PHONE_REQUEST";
export const UPDATE_PROFILE_USER_NEW_PHONE_SUCCESS =
  "UPDATE_PROFILE_USER_NEW_PHONE_SUCCESS";
export const UPDATE_PROFILE_USER_NEW_PHONE_FAILURE =
  "UPDATE_PROFILE_USER_NEW_PHONE_FAILURE";

export const CHANGE_USER_MPIN_REQUEST = "CHANGE_USER_MPIN_REQUEST";
export const CHANGE_USER_MPIN_SUCCESS = "CHANGE_USER_MPIN_SUCCESS";
export const CHANGE_USER_MPIN_FAILURE = "CHANGE_USER_MPIN_FAILURE";


export const CHANGEPASSWORD_REQUEST = "CHANGEPASSWORD_REQUEST";
export const CHANGEPASSWORD_SUCCESS = "CHANGEPASSWORD_SUCCESS";
export const CHANGEPASSWORD_FAILURE = "CHANGEPASSWORD_FAILURE";


export const CHECKEMAILEXIST_REQUEST = "CHECKEMAILEXIST_REQUEST";
export const CHECKEMAILEXIST_SUCCESS = "CHECKEMAILEXIST_SUCCESS";
export const CHECKEMAILEXIST_FAILURE = "CHECKEMAILEXIST_FAILURE";

export const CREATEPASSWORD_FORGET_REQUEST = "CREATEPASSWORD_FORGET_REQUEST";
export const CREATEPASSWORD_FORGET_SUCCESS = "CREATEPASSWORD_FORGET_SUCCESS";
export const CREATEPASSWORD_FORGET_FAILURE = "CREATEPASSWORD_FORGET_FAILURE";


export const SENDGROUPMESSAGE_REQUEST = "SENDGROUPMESSAGE_REQUEST";
export const SENDGROUPMESSAGE_SUCCESS = "SENDGROUPMESSAGE_SUCCESS";
export const SENDGROUPMESSAGE_FAILURE = "SENDGROUPMESSAGE_FAILURE";

export const GETGROUPMESSAGE_REQUEST = "GETGROUPMESSAGE_REQUEST";
export const GETGROUPMESSAGE_SUCCESS = "GETGROUPMESSAGE_SUCCESS";
export const GETGROUPMESSAGE_FAILURE = "GETGROUPMESSAGE_FAILURE";


export const GETGROUPLIST_REQUEST = "GETGROUPLIST_REQUEST";
export const GETGROUPLIST_SUCCESS = "GETGROUPLIST_SUCCESS";
export const GETGROUPLIST_FAILURE = "GETGROUPLIST_FAILURE";

export const GETCOMMUNITYLIST_REQUEST = "GETCOMMUNITYLIST_REQUEST";
export const GETCOMMUNITYLIST_SUCCESS = "GETCOMMUNITYLIST_SUCCESS";
export const GETCOMMUNITYLIST_FAILURE = "GETCOMMUNITYLIST_FAILURE";


export const GETGROUP_DETAILS_REQUEST = "GETGROUP_DETAILS_REQUEST";
export const GETGROUP_DETAILS_SUCCESS = "GETGROUP_DETAILS_SUCCESS";
export const GETGROUP_DETAILS_FAILURE = "GETGROUP_DETAILS_FAILURE";


export const ADD_GROUP_MEMEBERS_REQUEST = "ADD_GROUP_MEMEBERS_REQUEST";
export const ADD_GROUP_MEMEBERS_SUCCESS = "ADD_GROUP_MEMEBERS_SUCCESS";
export const ADD_GROUP_MEMEBERS_FAILURE = "ADD_GROUP_MEMEBERS_FAILURE";

export const GET_USER_SLAM_QUESTIONS_REQUEST = "GET_USER_SLAM_QUESTIONS_REQUEST";
export const GET_USER_SLAM_QUESTIONS_SUCCESS = "GET_USER_SLAM_QUESTIONS_SUCCESS";
export const GET_USER_SLAM_QUESTIONS_FAILURE = "GET_USER_SLAM_QUESTIONS_FAILURE";

export const SEND_USER_SLAM_QUESTIONS_REQUEST = "SEND_USER_SLAM_QUESTIONS_REQUEST";
export const SEND_USER_SLAM_QUESTIONS_SUCCESS = "GET_USER_SLAM_QUESTIONS_FAILURE";
export const SEND_USER_SLAM_QUESTIONS_FAILURE = "SEND_USER_SLAM_QUESTIONS_FAILURE";


export const SEND_USER_SLAM_QUESTIONS_CHAT_SUCCESS = "SEND_USER_SLAM_QUESTIONS_CHAT_SUCCESS";
export const SEND_USER_SLAM_QUESTIONS_CHAT_REQUEST = "SEND_USER_SLAM_QUESTIONS_CHAT_REQUEST";
export const SEND_USER_SLAM_QUESTIONS_CHAT_FAILURE = "SEND_USER_SLAM_QUESTIONS_CHAT_FAILURE";

export const SEND_USER_SLAM_QUESTIONS__ANSWER_REQUEST = "SEND_USER_SLAM_QUESTIONS__ANSWER_REQUEST";
export const SEND_USER_SLAM_QUESTIONS__ANSWER_SUCCESS = "SEND_USER_SLAM_QUESTIONS__ANSWER_SUCCESS";
export const SEND_USER_SLAM_QUESTIONS__ANSWER_FAILURE = "SEND_USER_SLAM_QUESTIONS__ANSWER_FAILURE";


export const GET_STICKERS_ARRAY_REQUEST = "GET_STICKERS_ARRAY_REQUEST";
export const GET_STICKERS_ARRAY_SUCCESS = "GET_STICKERS_ARRAY_SUCCESS";
export const GET_STICKERS_ARRAY_FAILURE = "SEND_USER_SLAM_QUESTIONS__ANSWER_FAILURE";

export const GET_WALLPAPER_ARRAY_REQUEST = "GET_WALLPAPER_ARRAY_REQUEST";
export const GET_WALLPAPER_ARRAY_SUCCESS = "GET_WALLPAPER_ARRAY_SUCCESS";
export const GET_WALLPAPER_ARRAY_FAILURE = "GET_WALLPAPER_ARRAY_FAILURE";

export const GET_SLAM_CONVO_ARRAY_REQUEST = "GET_SLAM_CONVO_ARRAY_REQUEST";
export const GET_SLAM_CONVO_ARRAY_SUCCESS = "GET_SLAM_CONVO_ARRAY_SUCCESS";
export const GET_SLAM_CONVO_ARRAY_FAILURE = "GET_SLAM_CONVO_ARRAY_FAILURE";

export const SEND_COMMUNITY_MESSAGE_REQUEST = "SEND_COMMUNITY_MESSAGE_REQUEST";
export const SEND_COMMUNITY_MESSAGE_SUCCESS = "SEND_COMMUNITY_MESSAGE_SUCCESS";
export const SEND_COMMUNITY_MESSAGE_FAILURE = "SEND_COMMUNITY_MESSAGE_FAILURE";


export const GET_COMMUNITY_MESSAGE_REQUEST = "GET_COMMUNITY_MESSAGE_REQUEST";
export const GET_COMMUNITY_MESSAGE_SUCCESS = "GET_COMMUNITY_MESSAGE_SUCCESS";
export const GET_COMMUNITY_MESSAGE_FAILURE = "GET_COMMUNITY_MESSAGE_FAILURE";



export const CHANGE_WALLPAPER_REQUEST = "CHANGE_WALLPAPER_REQUEST";
export const CHANGE_WALLPAPER_SUCCESS = "CHANGE_WALLPAPER_SUCCESS";
export const CHANGE_WALLPAPER_FAILURE = "CHANGE_WALLPAPER_FAILURE";

export const REMOVEGROUP_MEMBERS_REQUEST = "REMOVEGROUP_MEMBERS_REQUEST";
export const REMOVEGROUP_MEMBERS_SUCCESS = "REMOVEGROUP_MEMBERS_SUCCESS";
export const REMOVEGROUP_MEMBERS_FAILURE = "REMOVEGROUP_MEMBERS_FAILURE";


export const GET_COMMUNITY_DETAILS_REQUEST = "GET_COMMUNITY_DETAILS_REQUEST";
export const GET_COMMUNITY_DETAILS_SUCCESS = "GET_COMMUNITY_DETAILS_SUCCESS";
export const GET_COMMUNITY_DETAILS_FAILURE = "GET_COMMUNITY_DETAILS_FAILURE";

export const REMOVE_GROUP_REQUEST = "REMOVE_GROUP_REQUEST";
export const REMOVE_GROUP_SUCCESS = "REMOVE_GROUP_SUCCESS";
export const REMOVE_GROUP_FAILURE = "REMOVE_GROUP_FAILURE";



export const GET_SITE_DETAILS_REQUEST = "GET_SITE_DETAILS_REQUEST";
export const GET_SITE_DETAILS_SUCCESS = "GET_SITE_DETAILS_SUCCESS";
export const GET_SITE_DETAILS_FAILURE = "GET_SITE_DETAILS_FAILURE";



export const ALLOW_COMMUNITY_FLAG_REQUEST = "ALLOW_COMMUNITY_FLAG_REQUEST";
export const ALLOW_COMMUNITY_FLAG_SUCCESS = "ALLOW_COMMUNITY_FLAG_SUCCESS";
export const ALLOW_COMMUNITY_FLAG_FAILURE = "ALLOW_COMMUNITY_FLAG_FAILURE";

export const UPDATE_USERTSTUS_REQUEST = "UPDATE_USERTSTUS_REQUEST";
export const UPDATE_USERTSTUS_SUCCESS = "UPDATE_USERTSTUS_SUCCESS";
export const UPDATE_USERTSTUS_FAILURE = "UPDATE_USERTSTUS_FAILURE";

export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USER_FAILURE = "GET_USER_FAILURE";

export const BLOCK_USER_REQUEST = "BLOCK_USER_REQUEST";
export const BLOCK_USERS_SUCCESS = "BLOCK_USERS_SUCCESS";
export const BLOCK_USER_FAILURE = "BLOCK_USER_FAILURE";

export const GET_BLOCK_USER_REQUEST = "GET_BLOCK_USER_REQUEST";
export const GET_BLOCK_USERS_SUCCESS = "GET_BLOCK_USERS_SUCCESS";
export const GET_BLOCK_USER_FAILURE = "GET_BLOCK_USER_FAILURE";

export const UNBLOCK_USER_REQUEST = "UNBLOCK_USER_REQUEST";
export const UNBLOCK_USER_SUCCESS = "UNBLOCK_USER_SUCCESS";
export const UNBLOCK_USER_FAILURE = "UNBLOCK_USER_FAILURE";

export const REPORT_USER_REQUEST = "REPORT_USER_REQUEST";
export const REPORT_USER_SUCCESS = "REPORT_USER_SUCCESS";
export const REPORT_USER_FAILURE = "REPORT_USER_FAILURE";


export const DELETE_MESSAGES_REQUEST = "DELETE_MESSAGES_REQUEST";
export const DELETE_MESSAGES_SUCCESS = "DELETE_MESSAGES_SUCCESS";
export const DELETE_MESSAGES_FAILURE = "DELETE_MESSAGES_FAILURE";


export const DELETE_GROUP_MESSAGES_REQUEST = "DELETE_GROUP_MESSAGES_REQUEST";
export const DELETE_GROUP_MESSAGES_SUCCESS = "DELETE_GROUP_MESSAGES_SUCCESS";
export const DELETE_GROUP_MESSAGES_FAILURE = "DELETE_GROUP_MESSAGES_FAILURE";


export const MUTE_MESSAGES_REQUEST = "MUTE_MESSAGES_REQUEST";
export const MUTE_MESSAGES_SUCCESS = "MUTE_MESSAGES_SUCCESS";
export const MUTE_MESSAGES_FAILURE = "MUTE_MESSAGES_FAILURE";

export const DELETE_MESSAGES_CONVO_REQUEST = "DELETE_MESSAGES_CONVO_REQUEST";
export const DELETE_MESSAGES_CONVO_SUCCESS = "DELETE_MESSAGES_CONVO_SUCCESS";
export const DELETE_MESSAGES_CONVO_FAILURE = "DELETE_MESSAGES_CONVO_FAILURE";

export const REACT_MESSAGES_CONVO_REQUEST = "REACT_MESSAGES_CONVO_REQUEST";
export const REACT_MESSAGES_CONVO_SUCCESS = "REACT_MESSAGES_CONVO_SUCCESS";
export const REACT_MESSAGES_CONVO_FAILURE = "REACT_MESSAGES_CONVO_FAILURE";

export const STAR_MESSAGES_CONVO_REQUEST = "STAR_MESSAGES_CONVO_REQUEST";
export const STAR_MESSAGES_CONVO_SUCCESS = "STAR_MESSAGES_CONVO_SUCCESS";
export const STAR_MESSAGES_CONVO_FAILURE = "STAR_MESSAGES_CONVO_FAILURE";

export const GET_STAR_MESSAGES_CONVO_REQUEST = "GET_STAR_MESSAGES_CONVO_REQUEST";
export const GET_STAR_MESSAGES_CONVO_SUCCESS = "GET_STAR_MESSAGES_CONVO_SUCCESS";
export const GET_STAR_MESSAGES_CONVO_FAILURE = "GET_STAR_MESSAGES_CONVO_FAILURE";

export const MAKE_FAV_MESSAGES_CONVO_REQUEST = "MAKE_FAV_MESSAGES_CONVO_REQUEST";
export const MAKE_FAV_MESSAGES_CONVO_SUCCESS = "MAKE_FAV_MESSAGES_CONVO_SUCCESS";
export const MAKE_FAV_MESSAGES_CONVO_FAILURE = "MAKE_FAV_MESSAGES_CONVO_FAILURE";

export const UN_STAR_MESSAGES_CONVO_REQUEST = "UN_STAR_MESSAGES_CONVO_REQUEST";
export const UN_STAR_MESSAGES_CONVO_SUCCESS = "UN_STAR_MESSAGES_CONVO_SUCCESS";
export const UN_STAR_MESSAGES_CONVO_FAILURE = "UN_STAR_MESSAGES_CONVO_FAILURE";

export const PIN_CHAT_CONVO_REQUEST = "PIN_CHAT_CONVO_REQUEST";
export const PIN_CHAT_CONVO_SUCCESS = "PIN_CHAT_CONVO_SUCCESS";
export const PIN_CHAT_CONVO_FAILURE = "PIN_CHAT_CONVO_FAILURE";

export const FORWARD_CHAT_CONVO_REQUEST = "FORWARD_CHAT_CONVO_REQUEST";
export const FORWARD_CHAT_CONVO_SUCCESS = "FORWARD_CHAT_CONVO_SUCCESS";
export const FORWARD_CHAT_CONVO_FAILURE = "FORWARD_CHAT_CONVO_FAILURE";

export const GET_OWN_STATUS_REQUEST = "GET_OWN_STATUS_REQUEST";
export const GET_OWN_STATUS_SUCCESS = "GET_OWN_STATUS_SUCCESS";
export const GET_OWN_STATUS_FAILURE = "GET_OWN_STATUS_FAILURE";


export const DELETE_OWN_STATUS_REQUEST = "DELETE_OWN_STATUS_REQUEST";
export const DELETE_OWN_STATUS_SUCCESS = "DELETE_OWN_STATUS_SUCCESS";
export const DELETE_OWN_STATUS_FAILURE = "DELETE_OWN_STATUS_FAILURE";


export const STORYLIST_OWN_STATUS_REQUEST = "STORYLIST_OWN_STATUS_REQUEST";
export const STORYLIST_OWN_STATUS_SUCCESS = "STORYLIST_OWN_STATUS_SUCCESS";
export const STORYLIST_OWN_STATUS_FAILURE = "STORYLIST_OWN_STATUS_FAILURE";

export const STORY_LIKE_STATUS_REQUEST = "STORY_LIKE_STATUS_REQUEST";
export const STORY_LIKE_STATUS_SUCCESS = "STORY_LIKE_STATUS_SUCCESS";
export const STORY_LIKE_STATUS_FAILURE = "STORY_LIKE_STATUS_FAILURE";

